import os


PROJECT_ID = os.getenv("PROJECT_ID")
TOPIC_NAME = os.getenv("DRONE_POSITIONS_TOPIC")
SUBSCRIPTION_NAME = os.getenv("DRONE_POSITIONS_SUBSCRIPTION")
DATASET_NAME = os.getenv("DRONE_DATASET_NAME")
TABLE_NAME = os.getenv("DRONE_POSITIONS_TABLE_NAME")

TABLE_ID = f"{PROJECT_ID}.{DATASET_NAME}.{TABLE_NAME}"
TOPIC_PATH = f"projects/{PROJECT_ID}/topics/{TOPIC_NAME}" 
SUBSCRIPTION_PATH = f"projects/{PROJECT_ID}/subscriptions/{SUBSCRIPTION_NAME}"
