apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-deployment
  namespace: ns-drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-app
  template:
    metadata:
      labels:
        app: drone-app
    spec:
      serviceAccountName: drone-ksa
      containers:
      - name: drone-app
        image: europe-central2-docker.pkg.dev/drone-navigation-428814/drone-repo/drone-app:v1
        envFrom:
        - configMapRef:
            name: drone-env-vars
